<?php
/* @var \Magento\Backend\Block\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>

<button style="display: none;" id="pre_save_popup_display" title="<?= $escaper->escapeHtml(__('Save')) ?>" type="button" class="scalable primary">
    <span><?= $escaper->escapeHtml(__('Save')) ?></span>
</button>
<button style="display: none;" id="pre_save_continue_popup_display" title="<?= $escaper->escapeHtml(__('Save and Continue Edit')) ?>" type="button">
    <span><?= $escaper->escapeHtml(__('Save and Continue Edit')) ?></span>
</button>
<script type="text/x-magento-init">
    {
        "body": {
            "awClAddDueDateRestartModal": {}
        }
    }
</script>
