<?php
use Aheadworks\Ca\ViewModel\Company\Customer;
use Magento\Framework\View\Element\Template;

/**
 * @var Customer $customerViewModel
 * @var Template $block
 */

$customerViewModel = $block->getCustomerViewModel();
?>
<?php if ($customerViewModel->isAdminChangingAllowed()): ?>
    <!-- ko scope: 'aw_ca_change_company_admin' -->
        <!-- ko if: hasTemplate() -->
            <!-- ko template: getTemplate() --><!-- /ko -->
        <!-- /ko -->
    <!-- /ko -->
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?php /* @noEscape */ echo $block->getJsLayout() ?>
        }
    }
    </script>
<?php endif; ?>
