<?php
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/**
 * @var Template $block
 * @var Escaper $escaper
 */
?>
<label for="awctq_item_comment">
    <b><?= $escaper->escapeHtml(__('Comment:')) ?></b></label><Br>
    <textarea name="aw_ctq_quote_item_comment[<?= /* @noEscape */ $block->getItem()->getId() ?>]" maxlength="255"
              class="awctq_item_comment"><?= $escaper->escapeHtml($block->getItem()->getAwCtqItemComment()) ?></textarea>
</label>
