<?php
/* @var $block \Aheadworks\CreditLimit\Block\Customer\TotalList */
?>
<div class="block aw-cl__payment-form-wrapper">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Update the Balance')) ?></strong></div>
    <div class="block-content">
        <div class="aw-cl__payment-form" data-role="aw-cl__payment-form"  data-bind="scope: 'aw_cl_payment_form'">
            <!-- ko template: getTemplate() --><!-- /ko -->
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "[data-role=aw-cl__payment-form]": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        }
    }
</script>
