<?php
use Aheadworks\Ctq\Block\History\Render;

/**
 * @var Render $block
 */

$history = $block->getHistory();
?>
<?php if ($history->getOwnerName() && $history->getStatus()): ?>
    <div class="aw-ctq__history-title">
        <span class="aw-ctq-owner-name"><?= $block->escapeHtml($block->getHistoryViewModel()->getOwnerName($history)) ?></span>
        <span class="aw-ctq-status"><?= /* @noEscape */ $block->getHistoryViewModel()->getStatusFormatted($history->getStatus()) ?></span>
        <span class="aw-ctq-created-date"><?= /* @noEscape */ $block->getHistoryViewModel()->getCreatedAtFormatted($history->getCreatedAt()) ?></span>
    </div>
<?php endif; ?>
<?php if ($history->getActions()): ?>
    <div class="aw-ctq__history-info">
        <?php foreach ($history->getActions() as $action): ?>
            <?= /* @noEscape */ $block->getActionHtml($action) ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
