<?php
/* @var $block \Aheadworks\Ctq\Block\Customer\Quote\Header */

// @codingStandardsIgnoreFile
$block->getDataProviderViewModel()->setMethodToLocateQuote($block->getMethodToLocateQuote());
$quote = $block->getDataProviderViewModel()->getQuote();
$cart = $block->getDataProviderViewModel()->getCart();
?>
<span class="aw-ctq__quote-status">
    <?= $block->escapeHtml($block->getQuoteViewModel()->getStatusLabel($quote->getStatus())) ?>
</span>

<div class="aw-ctq__quote-header">
    <div class="aw-ctq__quote-data">
        <div class="aw-ctq__quote-id">
            <label><?= $block->escapeHtml(__('Quote #:')) ?></label>
            <span><?= $block->escapeHtml($quote->getId()) ?></span>
        </div>
        <?php if ($quote->getOrderId()): ?>
            <div class="aw-ctq__quote-order-id">
                <label><?= $block->escapeHtml(__('Order:')) ?></label>
                <?php if ($quote->getCustomerId()): ?>
                    <a href="<?= $block->escapeUrl($block->getQuoteViewModel()->getOrderUrl($quote->getOrderId())) ?>" class="order-link">
                        <span><?= $block->escapeHtml($block->getQuoteViewModel()->getOrderIdFormatted($quote->getOrderId())) ?></span>
                    </a>
                <?php else: ?>
                    <span><?= $block->escapeHtml($block->getQuoteViewModel()->getOrderIdFormatted($quote->getOrderId())) ?></span>
                <?php endif; ?>
            </div>
        <?php endif; ?>
        <div class="aw-ctq__quote-created-date">
            <label><?= $block->escapeHtml(__('Created:')) ?></label>
            <span><?= $block->escapeHtml($block->getQuoteViewModel()->getCreatedAtFormatted($quote->getCreatedAt())) ?></span>
        </div>
        <?php if ($quote->getExpirationDate()): ?>
            <div class="aw-ctq__quote-expired-date">
                <label><?= $block->escapeHtml(__('Expired:')) ?></label>
                <span><?= $block->escapeHtml($block->getQuoteViewModel()->getExpiredDateFormatted($quote->getExpirationDate())) ?></span>
            </div>
        <?php endif; ?>
    </div>
    <div class="actions-toolbar">
        <?php foreach ($block->getQuoteViewModel()->prepareBuyerQuoteActions($quote, $cart) as $key => $quoteAction): ?>
            <?php $actionName = 'aw-ctq-button-' . $key; ?>
            <button data-role="<?= /* @noEscape */ $actionName ?>"
                    class="action <?= /* @noEscape */ $key == 0 ? 'primary' : '' ?> <?= /* @noEscape */ $actionName ?>"
                    <?php if ($quoteAction->getData('is_disabled')) :?> disabled="disabled"<?php endif; ?>>
                <span><?= $block->escapeHtml(__($quoteAction->getName())) ?></span>
            </button>
            <script type="text/x-magento-init">
                {
                    "[data-role=<?= /* @noEscape */ $actionName ?>": {
                        "awCtqButtonControl": {
                            "submitForm": {
                                "formSelector": "<?= /* @noEscape */ $block->getQuoteViewModel()->getFormSelector() ?>",
                                "actionType": "<?= /* @noEscape */ $quoteAction->getType() ?>",
                                "action": "<?= $block->escapeUrl($block->getQuoteViewModel()->getQuoteUrlByAction($quote, $quoteAction, $block->getMethodToLocateQuote())) ?>"
                            }
                        }
                    }
                }
            </script>
        <?php endforeach; ?>
    </div>
</div>