<?php
// @codingStandardsIgnoreFile

/**  @var $block \Aheadworks\Ctq\Block\Adminhtml\Quote\Edit\QuotedItems */
?>

<?php if($block->isAllowed()): ?>
    <div class="admin__page-section-title">
        <strong class="title"><?= /* @escapeNotVerified */ $block->getHeaderText() ?></strong>
        <div class="actions">
            <?= $block->getButtonsHtml() ?>
        </div>
    </div>
    <?= $block->getChildHtml() ?>
<?php else: ?>
    <div class="message">
        <div><?= $block->escapeHtml($block->getNotice()) ?></div>
    </div>
<?php endif; ?>

