<?php
/* @var $block \Magento\Framework\View\Element\Template */
/* @var $viewModel \Aheadworks\Ctq\ViewModel\Customer\Quote\DataProvider */
/* @var $itemViewModel \Aheadworks\Ctq\ViewModel\Customer\Export\Quote\Item */
/* @var $cart \Magento\Quote\Model\Quote */

// @codingStandardsIgnoreFile
$viewModel = $block->getDataProviderViewModel();
$viewModel->setMethodToLocateQuote($block->getMethodToLocateQuote());
$itemViewModel = $block->getItemViewModel();
$quote = $viewModel->getQuote();
$cart = $viewModel->getCart();
$items = $cart->getAllVisibleItems();
$calculator = $itemViewModel->getTotalCalculator();
?>
<div class="block-title">
    <span><?= $block->escapeHtml(__('Products')) ?></span>
</div>
<table class="products">
    <thead>
        <tr>
            <th><?= $block->escapeHtml(__('Product Name')) ?></th>
            <th><?= $block->escapeHtml(__('SKU')) ?></th>
            <th><?= $block->escapeHtml(__('Proposed Price')) ?></th>
            <th><?= $block->escapeHtml(__('Qty')) ?></th>
            <th><?= $block->escapeHtml(__('Subtotal')) ?></th>
            <th><?= $block->escapeHtml(__('Negotiated Discount')) ?></th>
            <th><?= $block->escapeHtml(__('Estimated Tax')) ?></th>
            <th><?= $block->escapeHtml(__('Raw Subtotal')) ?></th>
        </tr>
    </thead>
    <tbody>
        <?php /* @var $item \Magento\Quote\Model\Quote\Item */ ?>
        <?php foreach ($items as $item): ?>
        <tr>
            <td>
                <span><?= $block->escapeHtml($item->getName()) ?></span>
            </td>
            <td>
                <span>
                    <?= implode(
                            '<br />',
                            $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($item->getSku()))
                    ) ?>
                </span>
            </td>
            <td>
                <span><?= /* @escapeNotVerified */ $itemViewModel->formatPrice(
                        $calculator->calculateItemProposedPrice($item),
                        $cart->getStoreId() ?: $quote->getStoreId()
                    ) ?>
                </span>
            </td>
            <td class="qty">
                <span><?= $block->escapeHtml($item->getQty()) ?></span>
            </td>
            <td>
                <?= /* @escapeNotVerified */ $itemViewModel->formatPrice(
                        $item->getRowTotal(),
                    $cart->getStoreId() ?: $quote->getStoreId()
                ) ?>
            </td>
            <td>
                <?= /* @escapeNotVerified */ $itemViewModel->formatPrice(
                        -$calculator->calculateItemNegotiatedDiscount($item),
                    $cart->getStoreId() ?: $quote->getStoreId()
                ) ?>
            </td>
            <td>
                <?= /* @escapeNotVerified */ $itemViewModel->formatPrice(
                        $item->getTaxAmount(),
                    $cart->getStoreId() ?: $quote->getStoreId()
                ) ?>
            </td>
            <td>
                <?= /* @escapeNotVerified */ $itemViewModel->formatPrice(
                        $calculator->calculateItemRowSubtotal($item),
                    $cart->getStoreId() ?: $quote->getStoreId()
                ) ?>
            </td>
        <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4">
                <?= /* @escapeNotVerified */ __('Total %1 product(s)', count($items)) ?>
            </td>
            <td>
                <strong>
                    <?= /* @escapeNotVerified */ $itemViewModel->formatPrice(
                        $calculator->getSubtotal($cart),
                        $cart->getStoreId() ?: $quote->getStoreId()
                    ) ?>
                </strong>
            </td>
            <td>
                <strong>
                    <?= /* @escapeNotVerified */ $itemViewModel->formatPrice(
                            $calculator->getNegotiatedDiscountAmount($cart),
                        $cart->getStoreId() ?: $quote->getStoreId()
                    ) ?>
                </strong>
            </td>
            <td>
                <strong>
                    <?= /* @escapeNotVerified */ $itemViewModel->formatPrice(
                            $calculator->getEstimatedTaxTotal($cart),
                        $cart->getStoreId() ?: $quote->getStoreId()
                    ) ?>
                </strong>
            </td>
            <td>
                <strong>
                    <?= /* @escapeNotVerified */ $itemViewModel->formatPrice(
                            $calculator->calculateSubtotalInclDiscountAndTax($cart),
                        $cart->getStoreId() ?: $quote->getStoreId()
                    ) ?>
                </strong>
            </td>
        </tr>
    </tfoot>
</table>

<style type="text/css">
    .block-title {
        margin: 2.5rem 0 0.5rem 0;
        text-decoration: underline;
    }
    .products {
        width: 100%;
        border: 1px solid #CDCDCD;
        border-collapse: collapse;
        font-size: 10pt;
    }
    .products td, .products th {
        padding: 5px;
        border: 1px solid #CDCDCD;
    }
</style>