<?php
/* @var $block \Magento\Framework\View\Element\Template */
/* @var $viewModel \Aheadworks\Ctq\ViewModel\Customer\Quote\DataProvider */
/* @var $shippingViewModel \Aheadworks\Ctq\ViewModel\Customer\Export\Quote\Shipping */
/* @var $cart \Magento\Quote\Model\Quote */

// @codingStandardsIgnoreFile
$viewModel = $block->getDataProviderViewModel();
$viewModel->setMethodToLocateQuote($block->getMethodToLocateQuote());
$shippingViewModel = $block->getShippingViewModel();;
$cart = $viewModel->getCart();
?>
<?php if ($shippingViewModel->isShippingInfoSpecified($cart)): ?>
    <div class="block-title">
        <span><?= $block->escapeHtml(__('Shipping Information')) ?></span>
    </div>
    <div class="shipping-information">
        <div class="section shipping-address">
            <span class="title"><?= $block->escapeHtml(__('Shipping Address')) ?></span>
            <div class="address">
                <?= /* @escapeNotVerified */ $shippingViewModel->getFormattedAddress($cart) ?>
            </div>
        </div>
        <?php if ($shippingViewModel->getFormattedShippingMethod($cart)): ?>
            <div class="section shipping-method">
                <span class="title"><?= $block->escapeHtml(__('Shipping Method')) ?></span>
                <div class="description">
                    <?= /* @escapeNotVerified */ $shippingViewModel->getFormattedShippingMethod($cart) ?>
                </div>
            </div>
        <?php endif; ?>
    </div>

    <style type="text/css">
        .block-title {
            margin: 2.5rem 0 0.5rem 0;
            text-decoration: underline;
        }
        .section .title {
            font-weight: bold;
        }
        .section {
            display: inline-block;
        }
        .section.shipping-address {
            float: left;
            width: 50%;
        }
        .section.shipping-method {
            float: right;
            width: 50%;
        }
    </style>
<?php endif; ?>