<?php
/* @var $block \Magento\Framework\View\Element\Template */
/* @var $viewModel \Aheadworks\Ctq\ViewModel\Customer\Quote\DataProvider */
/* @var $totalViewModel \Aheadworks\Ctq\ViewModel\Customer\Export\Quote\Total */
/* @var $cart \Magento\Quote\Model\Quote */

// @codingStandardsIgnoreFile
$viewModel = $block->getDataProviderViewModel();
$viewModel->setMethodToLocateQuote($block->getMethodToLocateQuote());
$totalViewModel = $block->getTotalViewModel();;
$cart = $viewModel->getCart();
?>
<div class="block-title">
    <span><?= $block->escapeHtml(__('Quote Totals')) ?></span>
</div>
<table class="totals">
    <tbody>
    <?= /* @escapeNotVerified */ $totalViewModel->renderTotals($cart) ?>
    <?= /* @escapeNotVerified */ $totalViewModel->renderTotals($cart, 'footer') ?>
    </tbody>
</table>

<style type="text/css">
    .block-title {
        margin: 2.5rem 0 0.5rem 0;
        text-decoration: underline;
    }
    .totals {
        width: 100%;
        border: 1px solid #CDCDCD;
        border-collapse: collapse;
        font-size: 10pt;
    }
    .totals td, .totals th {
        padding: 5px;
        border: 1px solid #CDCDCD;
    }
</style>