<?php
use Aheadworks\Ctq\Block\Adminhtml\Quote\Edit\Shipping\Method\Form;
use Magento\Framework\Escaper;
// @codingStandardsIgnoreFile

/** @var $block Form */
/** @var Escaper $escaper */

?>
<?php $rate = $block->getRate();
$rateCode = $rate->getCode()
?>
<?php $isChecked = $block->isMethodActive($rateCode) ? 'checked="checked"' : '' ?>
    <input name="shipping[shipping_method]"
           id="shipping_method_<?= /* @escapeNotVerified */
           $rate->getCarrier(); ?>"
           type="radio"
           value="<?= /* @escapeNotVerified */
           $rateCode ?>"
           id="s_method_<?= /* @escapeNotVerified */
           $rateCode ?>"
        <?= /* @escapeNotVerified */
        $isChecked ?>
           class="admin__control-radio required-entry"
           data-mage-init='{
                            "awCtqCustomShippingSelector": {
                                  "errorText": {
                                        "price": "<?= $escaper->escapeHtml(__('The price must be a number.')) ?>"
                                    }
                            }
                      }'
    />
    <label class="admin__field-label " for="s_method_<?= /* @escapeNotVerified */ $rateCode ?>">
        <?= $escaper->escapeHtml($rate->getMethodTitle() ? $rate->getMethodTitle() : $rate->getMethodDescription()) ?>
    </label>
    <input name="shipping[shipping_custom_price]"
           id="aw_cqt_shipping_price"
           type="text"
           value="<?= /* @escapeNotVerified */ $block->convertPriceToCurrency($rate->getPrice()); ?>"
           class="admin__control-text"
           maxlength="255"
    />
    <div id="awctq-error-message">
        <div id="awctq-error-text"></div>
    </
    <div>
