<?php

use Aheadworks\Ctq\Block\Adminhtml\Quote\Edit\Shipping\Method\Form;
use Magento\Framework\Escaper;
// @codingStandardsIgnoreFile

/** @var $block Form */
/** @var Escaper $escaper */

?>
<?php $rate = $block->getRate() ?>
<?php $rateCode = $rate->getCode() ?>
<?php $isChecked = $block->isMethodActive($rateCode) ? 'checked="checked"' : '' ?>
<input name="shipping[shipping_method]"
       id="shipping_method_<?= /* @escapeNotVerified */ $rate->getCarrier(); ?>"
       type="radio"
       onclick="quote.setShippingMethod(this.value)"
       value="<?= /* @escapeNotVerified */ $rateCode ?>"
       id="s_method_<?= /* @escapeNotVerified */ $rateCode ?>"
    <?= /* @escapeNotVerified */ $isChecked ?>
       class="admin__control-radio required-entry"
/>
<label class="admin__field-label " for="s_method_<?= /* @escapeNotVerified */ $rateCode ?>">
    <?= $escaper->escapeHtml($rate->getMethodTitle() ? $rate->getMethodTitle() : $rate->getMethodDescription()) ?> -
    <strong>
        <?= /* @escapeNotVerified */ $block->getShippingPriceExclTax($rate); ?>
        <?php if ($block->isNeedToDisplayBothPrices($rate)): ?>
            (<?= /* @escapeNotVerified */ __('Incl. Tax') ?> <?= /* @escapeNotVerified */ $block->getShippingPriceExclTax($rate) ?>)
        <?php endif; ?>
    </strong>
</label>
