<?php
/** @var $block \Aheadworks\Ca\Block\Adminhtml\System\Config\Form\Field\Customization */

// @codingStandardsIgnoreFile
?>
<?php $htmlName = $block->getElement()->getName(); ?>
<div class="aw-ca__fields-customization">
    <div class="aw-ca__customization-note">
        <?= $block->escapeHtml(__('Define field names and drag and drop them to required position.')) ?>
    </div>
    <div>
        <table class="admin__control-table" data-mage-init='{"awCaDraggableFieldArray": {}}'>
            <tbody data-role="row-container">
            <?php foreach ($block->getFieldRows() as $fieldName): ?>
                <tr>
                    <td class="col-draggable">
                        <?php $sortOrder = $block->getFieldSortOrder($fieldName); ?>
                        <div data-role="draggable-handle" class="draggable-handle"
                             title="<?= $block->escapeHtml(__('Sort Rows')) ?>"></div>
                        <input
                            data-role="sort-order"
                            type="hidden"
                            name="<?= /* @noEscape */ $htmlName ?>[rows][<?= /* @noEscape */ $fieldName ?>][sort_order]"
                            value="<?= /* @noEscape */ $sortOrder ?>"/>
                    </td>
                    <td class="col-fields">
                        <?php
                            $defaultValues = $block->getFormFieldDefaultConfig($fieldName);
                            $formValues = $block->getFormFieldSavedConfig($fieldName);
                        ?>
                        <div class="field-item-<?php /* @noEscape */ echo $fieldName ?>" data-mage-init='{"awCaFieldMetaEdit": {}}'>
                            <label class="item-label<?php if ($formValues['required']): ?> required-mark<?php endif; ?>"
                                   for="<?= /* @noEscape */ $block->getInputHtmlId($fieldName, 'label') ?>"></label>
                            <input id="<?= /* @noEscape */ $block->getInputHtmlId($fieldName, 'label') ?>"
                                   name="<?= /* @noEscape */ $block->getInputHtmlName($fieldName, 'label', '__outer') ?>"
                                   value="<?= /* @noEscape */ $formValues['label'] ?>"
                                   placeholder="<?= /* @noEscape */ $defaultValues['label'] ?>"
                                   class="input-text required-entry"
                                   type="text"
                                <?php if (!$formValues['visible']): ?> disabled="disabled"<?php endif; ?>
                                   data-required="<?php if ($formValues['required']): ?>1<?php else: ?>0<?php endif; ?>"
                                   data-meta-field-name="label"/>
                            <input data-value-input-id="<?= /* @noEscape */ $block->getInputHtmlId($fieldName, 'label') ?>"
                                   type="hidden"
                                   name="<?= /* @noEscape */ $block->getInputHtmlName($fieldName, 'label') ?>"
                                   value="<?= /* @noEscape */ $formValues['label'] ?>"/>
                            <div class="edit-actions">
                                <?php foreach ($block->getBooleanMetaFields() as $metaField => $inputLabel): ?>
                                    <?php
                                        $metaValue = $formValues[$metaField] ? 1 : 0;
                                        $canModifyMeta = $block->canModifyMeta($fieldName, $metaField);
                                    ?>
                                    <?php if ($canModifyMeta): ?>
                                        <input type="checkbox"
                                               name="<?= /* @noEscape */ $block->getInputHtmlName($fieldName, $metaField, '__outer') ?>]"
                                               value="1"
                                               id="<?= /* @noEscape */ $block->getInputHtmlId($fieldName, $metaField) ?>"
                                            <?php if ($metaValue): ?> checked="checked"<?php endif; ?>
                                               data-meta-field-name="<?php /* @noEscape */ echo $metaField ?>"/>
                                        <label for="<?= /* @noEscape */ $block->getInputHtmlId($fieldName, $metaField) ?>" class="label">
                                            <span><?= $block->escapeHtml(__($inputLabel)) ?></span>
                                        </label>
                                    <?php endif; ?>
                                    <input
                                        <?php if ($canModifyMeta): ?>
                                            data-value-input-id="<?= /* @noEscape */ $block->getInputHtmlId($fieldName, $metaField) ?>"
                                        <?php endif; ?>
                                            type="hidden"
                                            name="<?= /* @noEscape */ $block->getInputHtmlName($fieldName, $metaField) ?>]"
                                            value="<?= /* @noEscape */ $metaValue ?>"/>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
