<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Framework\View\Element\Template */
?>
<div data-role="aw-ca-domain-management" data-bind="scope: 'aw_ca_domain_management'" class="aw-ca__domain-management">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "[data-role=aw-ca-domain-management]": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        }
    }
</script>
