<?php
// @codingStandardsIgnoreFile
/** @var $block \Magento\Framework\View\Element\Template */

/** @var Aheadworks\Ca\ViewModel\Company\Customer $customerViewModel */
$customerViewModel = $block->getCustomerViewModel();
?>
<?php if ($customerViewModel->isCurrentUserCompanyAdmin()): ?>
    <div class="block block-domains">
        <div class="block-title">
            <strong><?= $block->escapeHtml(__('Company Domains')) ?></strong>
        </div>
        <div class="block-content">
            <?= $block->getChildHtml() ?>
        </div>
    </div>
<?php endif; ?>

