<?php
// @codingStandardsIgnoreFile
/** @var $block \Aheadworks\CreditLimit\Block\Customer\BalanceHistory\Listing */
?>
<div class="block aw-ui-listing <?= /* @escapeNotVerified */ $block->getData('additionalClasses') ?>">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Credit History')) ?></strong></div>
    <div class="block-content">
        <?= /* @escapeNotVerified */ $block->renderApp(); ?>
    </div>
</div>